# Server
server.port=8080
server.address=0.0.0.0

# Spring Application
spring.application.name=Scraply
spring.config.import=optional:file:.env[.properties]

# Datasource
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Client URL
webapp.origin=${WEBAPP_ORIGIN}

# PostgreSQL Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JWT Configuration
jwt.secret=${JWT_SECRET}

# Expiration Times
jwt.expiration.user=15552000000
jwt.expiration.picker=2592000000
jwt.expiration.admin=86400000

# HttpOnly prevents JavaScript access (prevents XSS attacks)
security.jwt.cookie.http-only=true

# Secure flag ensures cookies are only sent over HTTPS (set to false in development if not using HTTPS)
security.jwt.cookie.secure=${JWT_COOKIE_SECURE}

# SameSite protection against CSRF attacks (Strict/Lax/None)
security.jwt.cookie.same-site=${JWT_COOKIE_SAME_SITE}