# Server
server.port=8080
server.address=0.0.0.0

# Spring Application
spring.application.name=Scraply
spring.config.import=optional:file:.env[.properties]

# Datasource
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# Disable SQL logging at logger level
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF

# Optional (for newer Hibernate versions)
logging.level.org.hibernate.orm.jdbc.bind=OFF


# SpringDoc / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# Logging
logging.level.root=INFO
logging.level.com.scraply=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.health.defaults.enabled=false
management.health.livenessState.enabled=true
management.health.db.enabled=false
management.health.redis.enabled=false




# Client URL
webapp.origin=${WEBAPP_ORIGIN}

# PostgreSQL Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JWT Configuration
jwt.secret=${JWT_SECRET}

# Expiration Times
jwt.expiration.user=15552000000
jwt.expiration.picker=2592000000
jwt.expiration.admin=86400000

# Agent Keys
agent.access_key=${AGENT_ACCESS_KEY}
agent.secret_key=${AGENT_SECRET_KEY}

# Google OAuth
google.client-id=${GOOGLE_CLIENT_ID}
google.client-secret=${GOOGLE_CLIENT_SECRET}

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=${REDIS_SSL}